-- MySQL Script generated by MySQL Workbench
-- Tue Apr  8 14:45:00 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Hospedes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Hospedes` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(100) NOT NULL,
  `telefone` VARCHAR(45) NOT NULL,
  `email` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Reservas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Reservas` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `id_hospedes` INT NOT NULL,
  `data_checkin` DATETIME NOT NULL,
  `data_checkout` DATETIME NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `id_hospedes_idx` (`id_hospedes` ASC) VISIBLE,
  CONSTRAINT `id_hospedes`
    FOREIGN KEY (`id_hospedes`)
    REFERENCES `mydb`.`Hospedes` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Quartos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Quartos` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `numero` VARCHAR(45) NOT NULL,
  `tipo` VARCHAR(45) NULL,
  `preco_diaria` DECIMAL(7,2) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Quartos_Reservados`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Quartos_Reservados` (
  `id_reserva` INT NOT NULL,
  `id_quarto` INT NOT NULL,
  INDEX `id_reserva_idx` (`id_reserva` ASC) VISIBLE,
  INDEX `id_quarto_idx` (`id_quarto` ASC) VISIBLE,
  CONSTRAINT `id_reserva`
    FOREIGN KEY (`id_reserva`)
    REFERENCES `mydb`.`Reservas` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `id_quarto`
    FOREIGN KEY (`id_quarto`)
    REFERENCES `mydb`.`Quartos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Pagamentos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Pagamentos` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `id_reserva` INT NOT NULL,
  `valor` DECIMAL(7,2) NOT NULL,
  `metodo_pagamento` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `id_reserva_idx` (`id_reserva` ASC) VISIBLE,
  CONSTRAINT `id_reserva`
    FOREIGN KEY (`id_reserva`)
    REFERENCES `mydb`.`Reservas` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

INSERT INTO Hospedes (nome, telefone, email) VALUES
('1', 'Carlos Silva', '11987654321', 'carlos@email.com'),
('2', 'Ana Souza', '11976543210', 'ana@email.com');

INSERT INTO Reservas (id_hospedes, data_checkin, data_checkout) VALUES
(1, '2025-04-10 14:00:00', '2025-04-15 12:00:00'),
(2, '2025-04-12 15:00:00', '2025-04-14 11:00:00');

INSERT INTO Quartos (id, numero, tipo, preco_diaria) VALUES
('1', '101', 'Solteiro', 150.00),
('2', '102', 'Casal', 250.00);

INSERT INTO Quartos_Reservados (id_reserva, id_quarto) VALUES
(1, 1),
(2, 2);

INSERT INTO Pagamentos (id_reserva, valor, metodo_pagmento) VALUES
(1, 750.00, 'Cartão de Crédito'),
(2, 500.00, 'Pix');

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
